package main.java.Almacen.model;
// Generated 2/10/2019 11:23:33 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "almacen")
public class Categoria implements java.io.Serializable {

	@Expose (serialize = true, deserialize = true) 
	private Integer categoriaId;
	
	
	@Expose (serialize = true, deserialize = true) 
	private String nombre;
	
	private Set<Subcategoria> subcategorias = new HashSet<Subcategoria>(0);

	public Categoria() {
	}

	public Categoria(String nombre) {
		this.nombre = nombre;
	}

	public Categoria(String nombre, Set<Subcategoria> subcategorias) {
		this.nombre = nombre;
		this.subcategorias = subcategorias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CategoriaID", unique = true, nullable = false)
	public Integer getCategoriaId() {
		return this.categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Subcategoria> getSubcategorias() {
		return this.subcategorias;
	}

	public void setSubcategorias(Set<Subcategoria> subcategorias) {
		this.subcategorias = subcategorias;
	}

}
