package main.java.Almacen.model;
// Generated 5/12/2019 02:23:59 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estadopedido generated by hbm2java
 */
@Entity
@Table(name = "estadopedido", catalog = "almacen", uniqueConstraints = @UniqueConstraint(columnNames = "NombreEstado"))
public class Estadopedido implements java.io.Serializable {

	private Integer estadoPedidoId;
	private String nombreEstado;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Estadopedido() {
	}

	public Estadopedido(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	public Estadopedido(String nombreEstado, Set<Pedido> pedidos) {
		this.nombreEstado = nombreEstado;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EstadoPedidoID", unique = true, nullable = false)
	public Integer getEstadoPedidoId() {
		return this.estadoPedidoId;
	}

	public void setEstadoPedidoId(Integer estadoPedidoId) {
		this.estadoPedidoId = estadoPedidoId;
	}

	@Column(name = "NombreEstado", unique = true, nullable = false, length = 20)
	public String getNombreEstado() {
		return this.nombreEstado;
	}

	public void setNombreEstado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadopedido")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
