package main.java.Almacen.model;
// Generated 6/12/2019 06:22:44 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lugar generated by hbm2java
 */
@Entity
@Table(name = "lugar", catalog = "almacen")
public class Lugar implements java.io.Serializable {

	private Integer lugarId;
	private String nombre;
	private String descripcion;

	public Lugar() {
	}

	public Lugar(String descripcion) {
		this.descripcion = descripcion;
	}

	public Lugar(String nombre, String descripcion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lugarId", unique = true, nullable = false)
	public Integer getLugarId() {
		return this.lugarId;
	}

	public void setLugarId(Integer lugarId) {
		this.lugarId = lugarId;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
