package main.java.Almacen.model;
// Generated 25/07/2021 16:18:00 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "almacen")
public class Proveedor implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String telefono;
	private String contacto;
	private String direccion;
	private String mail;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Proveedor() {
	}

	public Proveedor(String nombre, String telefono, String contacto, String direccion, String mail) {
		this.nombre = nombre;
		this.telefono = telefono;
		this.contacto = contacto;
		this.direccion = direccion;
		this.mail = mail;
	}

	public Proveedor(String nombre, String telefono, String contacto, String direccion, String mail,
			Set<Articulo> articulos) {
		this.nombre = nombre;
		this.telefono = telefono;
		this.contacto = contacto;
		this.direccion = direccion;
		this.mail = mail;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono", nullable = false, length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "contacto", nullable = false, length = 20)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "direccion", nullable = false, length = 50)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "mail", nullable = false, length = 30)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
