package main.java.Almacen.model;
// Generated 5/12/2019 02:23:59 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor", catalog = "almacen")
public class Proveedor implements java.io.Serializable {

	@Expose (serialize = true, deserialize = true) 
	private Integer provId;
	
	@Expose (serialize = true, deserialize = true) 
	private String provNombre;
	private String provTel;
	private String provContacto;
	private String provDireccion;
	private String provMail;
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Proveedor() {
	}

	public Proveedor(String provNombre, String provTel, String provContacto, String provDireccion, String provMail) {
		this.provNombre = provNombre;
		this.provTel = provTel;
		this.provContacto = provContacto;
		this.provDireccion = provDireccion;
		this.provMail = provMail;
	}

	public Proveedor(String provNombre, String provTel, String provContacto, String provDireccion, String provMail,
			Set<Articulo> articulos) {
		this.provNombre = provNombre;
		this.provTel = provTel;
		this.provContacto = provContacto;
		this.provDireccion = provDireccion;
		this.provMail = provMail;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProvID", unique = true, nullable = false)
	public Integer getProvId() {
		return this.provId;
	}

	public void setProvId(Integer provId) {
		this.provId = provId;
	}

	@Column(name = "ProvNombre", nullable = false, length = 30)
	public String getProvNombre() {
		return this.provNombre;
	}

	public void setProvNombre(String provNombre) {
		this.provNombre = provNombre;
	}

	@Column(name = "ProvTel", nullable = false, length = 30)
	public String getProvTel() {
		return this.provTel;
	}

	public void setProvTel(String provTel) {
		this.provTel = provTel;
	}

	@Column(name = "ProvContacto", nullable = false, length = 20)
	public String getProvContacto() {
		return this.provContacto;
	}

	public void setProvContacto(String provContacto) {
		this.provContacto = provContacto;
	}

	@Column(name = "ProvDireccion", nullable = false, length = 50)
	public String getProvDireccion() {
		return this.provDireccion;
	}

	public void setProvDireccion(String provDireccion) {
		this.provDireccion = provDireccion;
	}

	@Column(name = "ProvMail", nullable = false, length = 30)
	public String getProvMail() {
		return this.provMail;
	}

	public void setProvMail(String provMail) {
		this.provMail = provMail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
