package main.java.Almacen.model;
// Generated 2/10/2019 11:23:33 AM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * Subcategoria generated by hbm2java
 */
@Entity
@Table(name = "subcategoria", catalog = "almacen")
public class Subcategoria implements java.io.Serializable {
	
	@Expose (serialize = true, deserialize = true) 
	private Integer subId;
	
	@Expose (serialize = true, deserialize = true) 
	private Categoria categoria;
	
	@Expose (serialize = true, deserialize = true) 
	private String subNombre;
	
	
	private Set<Articulo> articulos = new HashSet<Articulo>(0);

	public Subcategoria() {
	}

	public Subcategoria(Categoria categoria, String subNombre) {
		this.categoria = categoria;
		this.subNombre = subNombre;
	}

	public Subcategoria(Categoria categoria, String subNombre, Set<Articulo> articulos) {
		this.categoria = categoria;
		this.subNombre = subNombre;
		this.articulos = articulos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SubId", unique = true, nullable = false)
	public Integer getSubId() {
		return this.subId;
	}

	public void setSubId(Integer subId) {
		this.subId = subId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SubPadre", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "SubNombre", nullable = false, length = 50)
	public String getSubNombre() {
		return this.subNombre;
	}

	public void setSubNombre(String subNombre) {
		this.subNombre = subNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategoria")
	public Set<Articulo> getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set<Articulo> articulos) {
		this.articulos = articulos;
	}

}
