package main.java.Almacen.model;
// Generated 12/11/2019 01:20:56 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuariosys generated by hbm2java
 */
@Entity
@Table(name = "usuariosys", catalog = "almacen")
public class Usuariosys implements java.io.Serializable {

	private int id;
	private Rol rol;
	private String username;
	private String password;

	public Usuariosys() {
	}

	public Usuariosys(int id, Rol rol, String username, String password) {
		this.id = id;
		this.rol = rol;
		this.username = username;
		this.password = password;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
