package main.java.Almacen.model;
// Generated 4/11/2019 12:28:02 PM by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.gson.annotations.Expose;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "almacen", uniqueConstraints = @UniqueConstraint(columnNames = "NombreUsuario"))
public class Usuario implements java.io.Serializable {

	@Expose (serialize = true, deserialize = true) 
	private Integer usuarioId;
	@Expose (serialize = true, deserialize = true) 
	private Area area;
	@Expose (serialize = true, deserialize = true) 
	private Rol rol;
	@Expose (serialize = true, deserialize = true) 
	private String nombreUsuario;
	private String nombre;
	private String apellido;
	private String email;
	@Expose (serialize = true, deserialize = true) 
	private boolean activo;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
	private Set<Area> areas = new HashSet<Area>(0);

	public Usuario() {
	}

	public Usuario(Area area, Rol rol, String nombreUsuario, String nombre, String apellido, String email,
			boolean activo) {
		this.area = area;
		this.rol = rol;
		this.nombreUsuario = nombreUsuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.activo = activo;
	}

	public Usuario(Area area, Rol rol, String nombreUsuario, String nombre, String apellido, String email,
			boolean activo, Set<Pedido> pedidos, Set<Area> areas) {
		this.area = area;
		this.rol = rol;
		this.nombreUsuario = nombreUsuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.email = email;
		this.activo = activo;
		this.pedidos = pedidos;
		this.areas = areas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UsuarioID", unique = true, nullable = false)
	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Area", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "NombreUsuario", unique = true, nullable = false, length = 30)
	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false, length = 20)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "email", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Area> getAreas() {
		return this.areas;
	}

	public void setAreas(Set<Area> areas) {
		this.areas = areas;
	}

}
